import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateDefinition,regionalRows,directoryGroups,aliasTargets,hubState,validateRegionalPurchase,regionalMetadata,assertRegionalMetadata} from '../src/lib/regions.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),'utf8'));
const coverage=read('region-coverage'),policy=read('region-policy');
function fixture(){const c=structuredClone(coverage),p=structuredClone(policy);p.enabled=true;const r=c.representatives[0];r.status='approved';const page={...r,category:'regions',pageType:'regional-service',routeType:'category',scopeKey:p.scopeKey,status:'approved',approvalVerified:true,snapshotId:'test-only',snapshotHash:'a'.repeat(64),cardSummary:'Fixture'};const architecture={siteKey:p.siteKey,pages:[{...page,pageRole:'REGION_SERVICE_LANDING',parentHub:'/regions/',localizationPolicy:'local-required'}]};return {c,p,page,architecture};}
test('inventory is validated but disabled sources publish no regional route',()=>{validateDefinition(coverage,policy);assert.equal(policy.enabled,false);assert.deepEqual(directoryGroups([],read('architecture'),coverage,policy),[]);});
test('registered query produces exactly one canonical and no future links',()=>{const {c,p,page,architecture}=fixture();assert.equal(regionalRows([page],architecture,c,p).length,1);const groups=directoryGroups([page],architecture,c,p);assert.deepEqual([...new Set(groups.flatMap(d=>d.items.map(i=>i.page.url)))],[page.url]);assert.equal(groups.length,1);});
test('disabled scope and candidate representative cannot create a route',()=>{const {c,p,page,architecture}=fixture();assert.throws(()=>regionalRows([page],architecture,c,{...p,enabled:false}),/disabled/);c.representatives[0].status='candidate';assert.throws(()=>regionalRows([page],architecture,c,p),/approval/);});
test('approval, scope, semantics and canonical mismatches fail closed',()=>{for(const changes of [{approvalVerified:false},{scopeKey:'wrong'},{url:'/regions/alias/'},{pageType:'general-guide'},{snapshotHash:''}]){const {c,p,page,architecture}=fixture();assert.throws(()=>regionalRows([{...page,...changes}],architecture,c,p));}const f=fixture();f.architecture.pages[0].parentHub='/gift/';assert.throws(()=>regionalRows([f.page],f.architecture,f.c,f.p),/semantic/);});
test('untrusted official hosts and missing opt-in policy fail closed',()=>{const {c,p}=fixture();c.officialSourceUrls.push('https://ansan.go.kr.evil.example/');assert.throws(()=>validateDefinition(c,p),/untrusted/);assert.throws(()=>validateDefinition(coverage,{...policy,siteKey:'another-site'}),/site\/scope/);});
test('same unit never receives a second regional or existing canonical',()=>{const {c,p}=fixture();c.representatives.push({...c.representatives[0],pageKey:'duplicate',url:'/regions/duplicate/',slug:'duplicate',intentKey:'different',primaryKeyword:'different'});assert.throws(()=>validateDefinition(c,p),/canonical unit/);});
test('zero, thin, indexable and menu thresholds preserve preview priority',()=>{for(const [n,exists,indexable,menu] of [[0,false,false,false],[1,true,false,false],[2,true,false,false],[3,true,true,false],[4,true,true,false],[5,true,true,true]]){assert.deepEqual(hubState(n,true),{exists,indexable,menu,sitemap:indexable});assert.equal(hubState(n,false).indexable,false);assert.equal(hubState(n,false).sitemap,false);}});
test('Ansan Sa/Sai/Haeyang resolve only the approved Sa canonical; Seonbu is reserved',()=>{if(coverage.siteKey!=='ansan-flower-test')return;const {c,p,page,architecture}=fixture();for(const name of ['사동','사이동','해양동'])assert.deepEqual(aliasTargets(name,[page],architecture,c,p),['/regions/sangnok-sa/']);assert.deepEqual(aliasTargets('선부1동',[page],architecture,c,p),[]);assert.equal(c.representatives.find(r=>r.pageKey==='ansan-flower-launch-14').url,'/places/seonbu-home-shop-flower-delivery/');});
test('geography retains multi-district, eup/myeon/ri and unresolved alias evidence',()=>{if(coverage.siteKey==='hwaseong-flower'){assert.equal(coverage.units.find(u=>u.name==='능동').districtKeys.length,2);assert.ok(coverage.units.some(u=>u.unitType==='eup'&&u.legalRi.length));}if(coverage.siteKey==='yongin-flower-v2'){assert.ok(coverage.administrativeCrosswalk.some(a=>a.name==='양지면'&&a.relations[0].scope==='historical'));}if(coverage.siteKey==='seongnam-flower-v2'){const f=fixture();assert.deepEqual(aliasTargets('서현1동',[f.page],f.architecture,f.c,f.p),[]);assert.ok(coverage.administrativeCrosswalk.find(a=>a.name==='서현1동').unresolvedCandidateNames.length);}});

test('consultation-only cannot stand in for unmapped promised products',()=>{const page={pageType:'regional-service',regionalPurchaseMode:'consultation-only',regionalProductKeys:[],regionalProductFamilies:[]};validateRegionalPurchase(page,[],'서비스 가능 여부 상담');assert.throws(()=>validateRegionalPurchase(page,[],'꽃다발 주문'),/missing promised family/);assert.throws(()=>validateRegionalPurchase(page,[],'50,000원'),/price/);assert.throws(()=>validateRegionalPurchase({...page,regionalPurchaseMode:'catalog'},[],'꽃배달'),/missing product mapping/);});

test('ri aliases and multi-district units share a representative without inventing routes',()=>{if(coverage.siteKey==='yongin-flower-v2'){const f=fixture(),u=f.c.units.find(u=>u.name==='양지읍');f.c.representatives[0].unitKeys=[u.unitKey];assert.deepEqual(aliasTargets('양지면',[f.page],f.architecture,f.c,f.p),[f.page.url]);assert.deepEqual(aliasTargets(u.legalRi[0],[f.page],f.architecture,f.c,f.p),[f.page.url]);}if(coverage.siteKey==='hwaseong-flower'){const f=fixture(),u=f.c.units.find(u=>u.name==='능동');f.c.representatives[0].unitKeys=[u.unitKey];assert.equal(directoryGroups([f.page],f.architecture,f.c,f.p).length,2);assert.deepEqual(aliasTargets('능동',[f.page],f.architecture,f.c,f.p),[f.page.url]);}});

test('ordinary Korean price, guarantee and spaced-family claims cannot use consultation-only',()=>{const page={pageType:'regional-service',regionalPurchaseMode:'consultation-only',regionalProductKeys:[],regionalProductFamilies:[]};for(const text of ['가격은 5만원입니다.','가격은 5.5만 원입니다.','오늘 도착을 보장합니다.','전 지역 배송을 보장합니다.','꽃 다발을 주문할 수 있습니다.','꽃 바구니를 주문하세요.','무료 배송입니다.'])assert.throws(()=>validateRegionalPurchase(page,[],text),/missing promised family|price\/delivery/);for(const text of ['주소와 희망 시간을 알려 주시면 서비스 가능 여부를 상담합니다.','배송 가능 여부와 추가비용은 상담 후 확인하세요.','당일 배송을 보장하지 않습니다.','도착을 보장할 수 없습니다.','무료 배송이 아닙니다.'])assert.doesNotThrow(()=>validateRegionalPurchase(page,[],text));});

test('reviewed purchase/image binding matches every derived field, including policy-only drift',()=>{const f=fixture();const products=[{key:'sku',family:'funeral',sourceUrl:'https://fwith.co.kr/'}];f.p.visualBindings=[{pageKey:f.page.pageKey,status:'approved',assetType:'brand',verifiedAt:'2026-10-03',image:'/images/test.png',alt:'Test',sha256:'a'.repeat(64),sourceUrl:'https://fwith.co.kr/',width:1,height:1,type:'image/png',purchaseMode:'consultation-only',productKeys:[]}];const row={...f.page,...regionalMetadata(f.c,f.p,products,f.page.pageKey)};assertRegionalMetadata(row,f.c,f.p,products);f.p.visualBindings[0].purchaseMode='catalog';f.p.visualBindings[0].productKeys=['sku'];assert.throws(()=>assertRegionalMetadata(row,f.c,f.p,products),/binding drift/);const sales={...row,...regionalMetadata(f.c,f.p,products,f.page.pageKey)};assertRegionalMetadata(sales,f.c,f.p,products);f.p.visualBindings[0].purchaseMode='consultation-only';f.p.visualBindings[0].productKeys=[];assert.throws(()=>assertRegionalMetadata(sales,f.c,f.p,products),/binding drift/);for(const changes of [{regionalPurchaseMode:'catalog'},{regionalProductKeys:['sku']},{regionalProductFamilies:['funeral']},{ogImageWidth:2},{ogImageType:'image/jpeg'},{regionUnitKeys:['wrong']},{scopeKey:'wrong'}])assert.throws(()=>assertRegionalMetadata({...row,...changes},f.c,f.p,products),/binding drift/);});
