import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import pages from '../src/data/manual-pages.json' with {type:'json'};
import proof from '../src/data/manual-provenance.json' with {type:'json'};
import products from '../src/data/products.json' with {type:'json'};
import {validateManualContract,digest} from '../src/lib/manual-contract.mjs';
const clone=x=>structuredClone(x);
const bytes=fs.readFileSync(new URL('../src/data/manual-pages.json',import.meta.url));
const approved=()=>({...clone(proof),independentReview:{status:'approved',contentHash:proof.contentHash,reviewerId:'independent-manual-review-20261007',reviewedAt:'2026-10-07',evidencePath:'test-only'}});
function mutation(fn){const p=clone(pages);fn(p);const b=Buffer.from(JSON.stringify(p));return [p,{...approved(),contentHash:digest(b),independentReview:{...approved().independentReview,contentHash:digest(b)}},b];}
test('candidate preview passes without production approval',()=>assert(validateManualContract(pages,proof,bytes,products)));
test('pending manual review blocks indexable production',()=>assert.throws(()=>validateManualContract(pages,proof,bytes,products,{indexable:true}),/review pending/));
test('approval metadata without actual evidence bytes is rejected',()=>assert.throws(()=>validateManualContract(pages,approved(),bytes,products,{indexable:true}),/actual evidence/));
test('content drift blocks even an approved review',()=>assert.throws(()=>validateManualContract(pages,approved(),Buffer.from('changed'),products,{indexable:true}),/digest drift/));
test('review digest mismatch fails closed',()=>{let x=approved();x.independentReview.contentHash='stale';assert.throws(()=>validateManualContract(pages,x,bytes,products,{indexable:true}),/bind current/);});
test('writer cannot act as own reviewer',()=>{let x=approved();x.independentReview.reviewerId=x.writerId;assert.throws(()=>validateManualContract(pages,x,bytes,products,{indexable:true}),/cannot approve/);});
test('fabricated frozen provenance is rejected',()=>{let [p,v,b]=mutation(x=>x[0].snapshotId='fake');assert.throws(()=>validateManualContract(p,v,b,products),/Fabricated/);});
test('wrong SKU and intent is rejected',()=>{let [p,v,b]=mutation(x=>x[0].productKeys=['congrats-basic']);assert.throws(()=>validateManualContract(p,v,b,products),/SKU\/intent/);});
test('candidate environment flag never substitutes for approval',()=>{process.env.ALLOW_MANUAL_CANDIDATE='1';assert.throws(()=>validateManualContract(pages,proof,bytes,products,{indexable:true}),/review pending/);delete process.env.ALLOW_MANUAL_CANDIDATE;});
test('venue with wrong flower intent is rejected',()=>{let [p,v,b]=mutation(x=>{const row=x.find(p=>p.pageType==='event-venue');row.visualIntent='performance_venue';row.productKeys=['bouquet-happiness','bouquet-blue'];});assert.throws(()=>validateManualContract(p,v,b,products));});
